---
title: "Ventura River Discharge"
author: "Amritpal Sandhu"
date: "2022-08-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dataRetrieval)
library(tidyverse)
library(metajam)
library(devtools)

# Ventura River

siteNumber <- "11118500"
parameterCd <- "00060"  # Discharge
startDate <- "2019-10-01"  
endDate <- "2020-10-05" 

discharge <- readNWISdv(siteNumber = "11118500", 
                    parameterCd = "00060", startDate ="2019-10-01", endDate = "2020-10-05")
```

```{r}
ggplot(data = discharge, aes(x = Date, y = X_00060_00003)) + geom_line() + labs(y = "Discharge", x = "Date")
```

# Exercise 2

```{r}
link <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A7fc6f6db-c5ea-426a-a743-1f2edafb43b8"

path <- "~/eds_214_day3/eds_214_day3_handson/api_practice/"

# Download data
download_d1_data(link, path)

# Read in the data
data <- read_d1_files("~/eds_214_day3/eds_214_day3_handson/api_practice/doi_10.5063_F1CJ8BPH__household_language__csv/")

dataframe <- data$data

# Create a plot and write a piece of code that will compute the percentage of Alaskan household speaking only English for the year 2009 to 2015

english_speaking <- dataframe |>
  group_by(Year) |>
  summarize(english = speak_only_english/total) |>
  filter(Year = 2009:2015)

```

